In [ ]:
!pip3 install numpy

In [1]:
import numpy as np

In [2]:
a=np.arange(0,21,1)

In [3]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
a[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
#a[2:10:2]

array([2, 4, 6, 8])